### ISSUE TITLE
Synchronize window resizing on Mac

### ISSUE THREAD

**Issue by evgenyzinoviev** [electron/brightray#196]
Hi all.

Will adding support of this https://code.google.com/p/chromium/issues/detail?id=531831 to brightray fix this https://github.com/atom/electron/issues/3615?

I'm highly interested in that.

**Comment by zcbenz** [comment]
Looks awesome to me! :+1:

**Comment by evgenyzinoviev** [comment]
So can you add it?

**Comment by zcbenz** [comment]
I'll add it to my TODO list, no estimate for finish date though.

**Comment by evgenyzinoviev** [comment]
Thanks!

**Comment by geeeeeeeeek** [comment]
@zcbenz Is there any update? I'm bothered by this issue recently.

**Comment by zcbenz** [comment]
After a closing look, I found actually the original Chromium issue was for their new UI framework on Mac, and after upgrading to Chrome 49, we already have synchronous window resizing in Electron.

**Comment by evgenyzinoviev** [comment]
Hmm, I can't confirm that it's working (tested on Electron 0.37.2).

**Comment by zcbenz** [comment]
I tested it by:
1. Opening the default app
2. Navigate to a complex site like amazon.com
3. Make sure devtools is closed
4. Resize the window and you can notice sync resizing behavior

**Comment by evgenyzinoviev** [comment]
Try to open more complex site like youtube.com: https://www.youtube.com/watch?v=D699kZYnWYg&feature=youtu.be

**Comment by zcbenz** [comment]
You will also get the same effect when opening Youtube in Chrome. The synchronous window resizing is not working perfectly, the best we can do is keep the same behavior with Chrome.

**Comment by davej** [comment]
This is working for manual resize using the cursor but still doesn't seem to be working with `win.setSize` with animate set to `true`. Tested on 0.37.7 with devtools closed, [here's a video](https://www.youtube.com/watch?v=y3hVFIaIEyE).

Let me know if I should create a new issue for this in Electron/Brightray.
