### ISSUE TITLE
run android apps on desktops with brightray?

### ISSUE THREAD

**Issue by joeblew99** [electron/brightray#240]
I want to be able to run android apps on desktops (windows, linux, osx).
i am raising this on the brightray issue list because i hope someone here knows if libchromiumcontent would allow this....

We all heard about how Google are using containers to run android on ChromeOS.

And we all saw how Docker is now able to run on OSX and Windows using:
https://github.com/docker/hyperkit

So does anyone know if Chromium Or brightray offers this, like how Chrome OS does ?

**Comment by paulcbetts** [comment]
It won't, sorry, libchromiumcontent is all about rendering web pages.
